name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "src/**/*"
      - "test/**/*"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: |
          pnpm install -g @liriliri/lsla
          pnpm install
          pnpm run ci
